#include <stdio.h>
#include <string.h>
#include <stdlib.h>

void CountingBases(char *alphabet) {

  int i;
  int adenine = 0;
  int cytosine = 0;
  int guanine = 0;
  int thymine = 0;
       
  for(i = 0; alphabet[i] != 0; ++i) {
  
    if(alphabet[i] == 'A') {
      ++adenine;
    }
    if(alphabet[i] == 'C'){
      ++cytosine;
    }
    if(alphabet[i] == 'G') { 
      ++guanine;
    }
    if(alphabet[i] == 'T') {
      ++thymine;
    } 
  
  }
  printf("ACGU: %d %d %d %d \n", adenine, cytosine, guanine, thymine);
}

int main() {
  int i;

  char m[] = "TTAGTCCACGTTCACGGTATTCCTACCAGACTTTCTTGAAGCACTATCGATAGTGGTGTAGGACTACCGTGTTCAGCATGTTTGCACCGCTAAATTACCTTTGACATACGTCTGCCTGGATTTAGTATGGAATGCATGTTGTTTCCCGGCGATGCCATTGCACCGGCCCCATTAATGATTTATAATTACTGGCACCTAGTGATTGTGCCAGTGAGTTATCCGATAAAAGCAGCATGAGCTTTCCCTTGGACATTACATGCACTATTTCAGCAGAGGAAACTCGACAAATTTGTCAGGACTCTTATACCACATAACCCTCGCGTGAGCCCACATTCAACCAATTCCAATGGATCACGCTGGGTATCCAAAGGCACTGCTGGTTCAACCATGATCCTCTGAACCGGCTCTGTCCCGTCTCTTCCAGGGAGCAGGAACTGGGTGTTTGGTAGACGAATCACGGACAATCGGGGAAACCTACTGTGACCTAAGCCAAACGTACGATTATCTCAGTAACGCCTCCCTGCCGGACCAGCTCCGGGTCTAATCTAAGCGTTGAGTGACTGATAACCACTGGGGGGAATAGTTTCAAATCTTATCATATACCCTTGCCTTACATTTTCGTGTAAGGTGTGGGAGATAAGCAGCCCAGCTACCGGGTCCTGCCTGATGACCGTATATCCCTGTCGCAGTCCGATCCATTCGCCCCCTGGGGGAAAACCTGGTAACGCGTGCGAATGCGAGTAATCCTGATACGCCCATCATTTCTATAGGTCGTACATGAGCGTGTTTACTGCGTGGCAAATCGATCTACAAGTCTGGCTGCCAACTGGGGAAACGAGAGAGAGACGCGGAACGAATAGGAGACGTGCACTAGCGTTGCATACATATTTCGTACTAGCACTAGCAAATGTTCACGGTATCTTGACTCGCATGCACC";  
  
  CountingBases(m);

 return 0;
}